"""
Real supplier display names aligned with public supply-chain disclosures.

Used by Neon seeding and trade-calibration supplier row generation.
"""

from __future__ import annotations

REAL_SUPPLIER_NAMES: dict[str, list[str]] = {
    "CN_Electronics": [
        "Foxconn Technology Group",
        "Pegatron Corporation",
        "Compal Electronics",
        "Wistron Corporation",
        "TSMC",
        "BOE Technology Group",
        "Luxshare Precision",
        "Goertek Inc",
        "BYD Electronic",
        "Sunny Optical",
        "Lens Technology",
        "AAC Technologies",
        "Tongda Group",
        "Zhejiang Crystal-Optech",
        "Truly International",
        "O-Film Group",
        "Biel Crystal",
        "Jabil Circuit China",
        "Flex Ltd China",
        "Flextronics Zhuhai",
        "Flextronics Shenzhen",
        "Qisda Corporation",
        "Inventec Corporation",
        "Quanta Computer Kunshan",
        "Delta Electronics China",
        "Lite-On Technology",
        "YAGEO Corporation",
        "Unimicron Technology",
        "Advanced Semiconductor Engineering",
        "Siliconware Precision",
    ],
    "CN_Apparel": [
        "Shenzhou International Group",
        "Pacific Textiles Holdings",
        "Crystal International Group",
        "Texhong Textile Group",
        "Nameson Holdings",
        "Regina Miracle International",
        "Eclat Textile",
        "Feng Tay Enterprises",
        "Pou Chen Corporation",
        "Yue Yuen Industrial",
        "Huali Industrial Group",
        "Stella International",
        "Kasen International Holdings",
        "Victory City International",
        "Lever Style Corporation",
        "TAL Apparel",
        "Sinomax Group",
        "Esquel Group",
        "Fang Brothers Group",
        "William Carter China",
    ],
    "CN_Auto Parts": [
        "CITIC Dicastal",
        "Minth Group",
        "Fuyao Glass Industry",
        "Nexteer Automotive China",
        "Yanfeng Automotive Interiors",
        "Joyson Safety Systems",
        "Sensata Technologies China",
        "Lear Corporation China",
        "Aptiv China",
        "BorgWarner China",
        "ZF China",
        "Bosch China",
        "Continental Automotive China",
        "Valeo China",
        "Plastic Omnium China",
        "Faurecia China",
        "Gentherm China",
        "Modine Manufacturing China",
        "Superior Industries China",
        "Meridian Lightweight Technologies",
    ],
    "CN_Food & Beverage": [
        "Yili Group",
        "Mengniu Dairy",
        "WH Group",
        "China Yurun Food Group",
        "New Hope Liuhe",
        "COFCO Corporation",
        "Bright Food Group",
        "Dali Foods Group",
        "Uni-President China",
        "Hengan International",
        "Want Want China Holdings",
        "Haitian International",
        "Foshan Haitian Flavouring",
        "Ting Hsin International",
        "Sichuan Teway Food Group",
        "Wens Foodstuff Group",
        "Sunner Development",
        "New Hope Dairy",
        "Feihe International",
        "Ausnutria Dairy Corporation",
    ],
    "CN_Chemicals": [
        "Sinopec Corp",
        "PetroChina",
        "Wanhua Chemical Group",
        "Rongsheng Petrochemical",
        "Hengli Petrochemical",
        "Shandong Hualu-Hengsheng Chemical",
        "Zhejiang NHU",
        "Jiangsu Yangnong Chemical",
        "Huntsman China",
        "BASF China",
        "Dow Chemical China",
        "LyondellBasell China",
        "Eastman Chemical China",
        "Celanese China",
        "Solvay China",
        "Lanxess China",
        "Clariant China",
        "Evonik China",
        "Arkema China",
        "Dupont China",
    ],
    "MX_Auto Parts": [
        "Nemak",
        "Vitro",
        "Grupo KUO",
        "Rassini",
        "Metalsa",
        "Katcon Global",
        "Grupo Industrial Saltillo",
        "Draxton",
        "DENSO Mexico",
        "Magna International Mexico",
        "Delphi Technologies Mexico",
        "Lear Corporation Mexico",
        "Aptiv Mexico",
        "Continental Mexico",
        "ZF Mexico",
        "Bosch Mexico",
        "Valeo Mexico",
        "Plastic Omnium Mexico",
        "Faurecia Mexico",
        "Motherson Sumi Mexico",
    ],
    "MX_Food & Beverage": [
        "Grupo Bimbo",
        "Gruma",
        "Sigma Alimentos",
        "Lala",
        "Jumex",
        "Bachoco",
        "Cuauhtémoc Moctezuma",
        "Grupo Herdez",
        "Genomma Lab Internacional",
        "Arca Continental",
        "Coca-Cola FEMSA",
        "Grupo Modelo",
        "Organización Cultiba",
        "Sabritas",
        "Grupo Lala",
        "La Costeña",
        "Del Valle",
        "Barcel",
        "Grupo San Marcos",
        "Conservas La Costeña",
    ],
    "MX_Apparel": [
        "Kaltex",
        "Coppel Manufacturing",
        "Hamco",
        "Grupo Carso Apparel",
        "Textiles Opichen",
        "Confecciones Internacionales",
        "Grupo Industrial Saltillo Apparel",
        "Global Denim",
        "Parras Cone de Mexico",
        "Tavex Mexico",
        "Cone Denim Mexico",
        "Propimex",
        "Textil del Valle",
        "Industrias Cannon",
        "Grupo Textil Providencia",
        "Nylstar Mexico",
        "Compañía Industrial de Orizaba",
        "Roc-Sil Textiles",
        "Fibras Texcel",
        "Hilasal",
    ],
    "CA_Auto Parts": [
        "Magna International",
        "Martinrea International",
        "ABC Technologies",
        "Shawflex",
        "Linamar Corporation",
        "Multimatic",
        "Stackpole International",
        "Woodbridge Foam",
        "Ventra Industries Canada",
        "Flex-N-Gate Canada",
        "Meridian Lightweight Technologies Canada",
        "Cosma International",
        "Inteva Products Canada",
        "Martinrea Honsel",
        "Shur-Lok Canada",
        "Wescast Industries",
        "Ventra Industries",
        "Magna Closures",
        "Magna Exteriors",
        "Decoma International",
    ],
    "CA_Industrial Machinery": [
        "Bombardier",
        "CAE Inc",
        "SNC-Lavalin",
        "Toromont Industries",
        "Finning International",
        "Wajax Corporation",
        "Russel Metals",
        "Norbord",
        "Canfor Corporation",
        "West Fraser Timber",
        "Stella-Jones",
        "Canam Group",
        "Strad Inc",
        "Maxim Power Corp",
        "Bird Construction",
        "PCL Constructors",
        "EllisDon Corporation",
        "Graham Corporation Canada",
        "Stuart Olson",
        "Aecon Group",
    ],
    "DE_Auto Parts": [
        "Robert Bosch GmbH",
        "Continental AG",
        "ZF Friedrichshafen",
        "Mahle GmbH",
        "Schaeffler AG",
        "Hella GmbH",
        "Brose Fahrzeugteile",
        "Webasto SE",
        "KION Group",
        "Knorr-Bremse AG",
        "Wabco Holdings Germany",
        "Leoni AG",
        "ElringKlinger AG",
        "Stabilus GmbH",
        "Grammer AG",
        "Norma Group",
        "SAF-Holland",
        "Frauenthal Holding",
        "Polytec Group Germany",
        "Georg Fischer Germany",
    ],
    "DE_Industrial Machinery": [
        "Siemens AG",
        "ThyssenKrupp AG",
        "Voith GmbH",
        "Trumpf GmbH",
        "Körber AG",
        "Heidelberger Druckmaschinen",
        "KUKA AG",
        "Gebr. Pfeiffer SE",
        "Windmöller & Hölscher",
        "Haver & Boecker",
        "BMA AG",
        "Linde Engineering",
        "GEA Group",
        "Andritz Germany",
        "Sulzer Germany",
        "Atlas Copco Germany",
        "Sandvik Germany",
        "Alfa Laval Germany",
        "SPX FLOW Germany",
        "Dover Corporation Germany",
    ],
    "DE_Chemicals": [
        "BASF SE",
        "Bayer AG",
        "Lanxess AG",
        "Evonik Industries",
        "Henkel AG",
        "Wacker Chemie AG",
        "Brenntag SE",
        "Symrise AG",
        "Merck KGaA",
        "Covestro AG",
        "K+S AG",
        "Clariant Germany",
        "Solvay Germany",
        "Degussa Germany",
        "Celanese Germany",
        "Air Liquide Germany",
        "Linde plc Germany",
        "Air Products Germany",
        "Praxair Germany",
        "Nippon Gases Germany",
    ],
    "VN_Electronics": [
        "Samsung Electronics Vietnam",
        "LG Electronics Vietnam",
        "Intel Vietnam",
        "Canon Vietnam",
        "Panasonic Vietnam",
        "Foxconn Vietnam",
        "Luxshare Vietnam",
        "Goertek Vietnam",
        "AMS Vietnam",
        "Jabil Vietnam",
        "Flextronics Vietnam",
        "Nidec Vietnam",
        "Mabuchi Motor Vietnam",
        "Hosiden Vietnam",
        "Kyocera Vietnam",
        "TDK Vietnam",
        "Murata Vietnam",
        "Alps Alpine Vietnam",
        "Yazaki Vietnam",
        "Sumitomo Vietnam",
    ],
    "VN_Apparel": [
        "Viet Tien Garment Corporation",
        "May 10 Corporation",
        "Nha Be Garment Corporation",
        "Thanh Cong Textile Garment",
        "Hoa Tho Textile Garment",
        "Phong Phu Corporation",
        "Saigon 3 Garment",
        "An Phuoc Garment",
        "Vinatex",
        "TNG Investment and Trading",
        "Garment 10 Corporation",
        "Duc Giang Corporation",
        "Hung Yen Garment",
        "Hanosimex",
        "Bong Sen Garment",
        "Maxport Limited Vietnam",
        "Crystal Martin Vietnam",
        "Eclat Vietnam",
        "Coats Vietnam",
        "YKK Vietnam",
    ],
    "JP_Auto Parts": [
        "Toyota Industries Corporation",
        "Denso Corporation",
        "Aisin Corporation",
        "Jtekt Corporation",
        "Toyota Boshoku",
        "Sumitomo Electric Industries",
        "Yazaki Corporation",
        "Tokai Rika",
        "Toyoda Gosei",
        "Stanley Electric",
        "Koito Manufacturing",
        "Murakami Corporation",
        "Futaba Industrial",
        "Tachi-S",
        "Kojima Industries",
        "GS Yuasa",
        "Maruyasu Industries",
        "Toyoda Iron Works",
        "Toyo Tire Corporation",
        "Sumitomo Riko",
    ],
    "JP_Electronics": [
        "Sony Corporation",
        "Panasonic Holdings",
        "Murata Manufacturing",
        "TDK Corporation",
        "Nidec Corporation",
        "Kyocera Corporation",
        "Alps Alpine",
        "Mabuchi Motor",
        "Hosiden Corporation",
        "Minebea Mitsumi",
        "Rohm Semiconductor",
        "Omron Corporation",
        "Keyence Corporation",
        "Hirose Electric",
        "Molex Japan",
        "TE Connectivity Japan",
        "Fujikura Ltd",
        "Sumitomo Electric",
        "Hitachi Metals",
        "Shin-Etsu Chemical",
    ],
    "KR_Electronics": [
        "Samsung SDI",
        "SK Hynix",
        "LG Display",
        "Samsung Electro-Mechanics",
        "LG Innotek",
        "Samsung Display",
        "Hyundai Mobis",
        "SK Innovation",
        "Hanon Systems",
        "LS Electric",
        "Doosan Bobcat Korea",
        "Hyosung Corporation",
        "Hana Microdisplay",
        "Korea Circuit",
        "Interflex",
        "BH Co Ltd",
        "Simmtech",
        "Daeduck Electronics",
        "Iljin Electric",
        "Wonik IPS",
    ],
    "IN_Pharmaceuticals": [
        "Sun Pharmaceutical Industries",
        "Dr. Reddys Laboratories",
        "Cipla Limited",
        "Lupin Limited",
        "Aurobindo Pharma",
        "Divi's Laboratories",
        "Biocon Limited",
        "Glenmark Pharmaceuticals",
        "Torrent Pharmaceuticals",
        "Alkem Laboratories",
        "Ipca Laboratories",
        "Cadila Healthcare",
        "Abbott India",
        "Pfizer India",
        "GlaxoSmithKline India",
        "Sanofi India",
        "Novartis India",
        "AstraZeneca India",
        "Johnson & Johnson India",
        "Roche India",
    ],
    "IN_Textiles": [
        "Welspun India",
        "Arvind Limited",
        "Raymond Limited",
        "Vardhman Textiles",
        "Trident Group",
        "Alok Industries",
        "Indo Count Industries",
        "Siyaram Silk Mills",
        "Bombay Dyeing",
        "Mafatlal Industries",
        "Nahar Industrial Enterprises",
        "Sutlej Textiles",
        "Himatsingka Seide",
        "BSL Limited",
        "Ambika Cotton Mills",
        "Nitin Spinners",
        "Banswara Syntex",
        "Pallonji Textiles",
        "Ginni Filaments",
        "Century Enka",
    ],
    "TW_Electronics": [
        "Taiwan Semiconductor Manufacturing (TSMC)",
        "Hon Hai Precision (Foxconn Taiwan)",
        "Pegatron Corporation Taiwan",
        "Quanta Computer",
        "Compal Electronics Taiwan",
        "Wistron Corporation Taiwan",
        "ASUSTeK Computer",
        "Acer Incorporated",
        "MediaTek Incorporated",
        "Realtek Semiconductor",
        "Novatek Microelectronics",
        "Silicon Motion Technology",
        "Himax Technologies",
        "Innolux Corporation",
        "AU Optronics",
        "Chunghwa Picture Tubes",
        "Advanced Semiconductor Engineering (ASE)",
        "Siliconware Precision Industries",
        "King Yuan Electronics",
        "Powertech Technology",
    ],
    "US_Consumer Goods": [
        "Procter & Gamble",
        "Colgate-Palmolive",
        "Church & Dwight",
        "Spectrum Brands",
        "Energizer Holdings",
        "Edgewell Personal Care",
        "Prestige Consumer Healthcare",
        "Central Garden Pet",
        "Energizer Brands",
        "Acco Brands",
        "Avery Dennison",
        "Sealed Air Corporation",
        "Berry Global Group",
        "Silgan Holdings",
        "AptarGroup",
        "Sonoco Products",
        "Greif Inc",
        "Pactiv Evergreen",
        "Graphic Packaging Holding",
        "WestRock Company",
    ],
    "US_Industrial Machinery": [
        "Caterpillar Inc",
        "Deere & Company",
        "Parker Hannifin",
        "Emerson Electric",
        "Eaton Corporation",
        "Illinois Tool Works",
        "Dover Corporation",
        "Rockwell Automation",
        "Roper Technologies",
        "Watts Water Technologies",
        "IDEX Corporation",
        "Mueller Water Products",
        "Enpro Industries",
        "Chart Industries",
        "Graham Corporation",
        "Thermon Group",
        "Lydall Inc",
        "Jason Industries",
        "NN Inc",
        "Haynes International",
    ],
}


def get_supplier_name(country: str, industry: str, used_names: set[str], index: int) -> str:
    """
    Resolve a display name for (country, industry), cycling the curated list and
    suffixing when a name is reused within the same seeding pass.
    """
    country = (country or "").strip()
    industry = (industry or "").strip() or "Electronics"

    key = f"{country}_{industry}"
    names = REAL_SUPPLIER_NAMES.get(key, [])

    if not names:
        for k, v in REAL_SUPPLIER_NAMES.items():
            if k.startswith(f"{country}_"):
                names = v
                break

    if not names:
        for k, v in REAL_SUPPLIER_NAMES.items():
            if k.endswith(f"_{industry}"):
                names = v
                break

    if names:
        base_name = names[index % len(names)]
        if base_name in used_names:
            suffix_num = (index // len(names)) + 2
            name = f"{base_name} ({suffix_num})"
        else:
            name = base_name
        used_names.add(name)
        return name

    return f"Supplier {country}-{index:04d}"
