name: carbonpulse
version: "1.0.0"
config-version: 2
profile: carbonpulse

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

vars:
  carbonpulse_use_live_silver: false

models:
  carbonpulse:
    staging:
      +materialized: view
    intermediate:
      +materialized: ephemeral
    marts:
      +materialized: table
